// Generated by CoffeeScript 1.7.1
(function() {
  window.UserProfilesApp = angular.module("UserProfilesApp", []);

  window.UserProfilesApp.service('userProfilesService', [
    '$http', function($http) {
      return {
        loadMyProfile: function(onSuccess, onError) {
          var properties;
          properties = ShareCoffee.REST.build.read["for"].angularJS({
            url: ShareCoffee.Url.GetMyProperties
          });
          return $http(properties).success(onSuccess).error(onError);
        }
      };
    }
  ]);

  window.UserProfilesApp.controller('userProfilesController', [
    '$scope', 'userProfilesService', function($scope, userProfilesService) {
      $scope.name = '';
      $scope.email = '';
      $scope.job = '';
      $scope.profilePicture = '';
      $scope.onProfileLoaded = function(data) {
        $scope.name = data.d.DisplayName;
        $scope.job = data.d.Title;
        $scope.email = data.d.Email;
        return $scope.profilePicture = data.d.PictureUrl;
      };
      $scope.onError = function(a, b, c) {
        console.log(a);
        console.log(b);
        return console.log(c);
      };
      $scope.loadProfile = function() {
        return userProfilesService.loadMyProfile($scope.onProfileLoaded, $scope.onError);
      };
      return $scope.loadProfile();
    }
  ]);

}).call(this);
